# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # build_app(scheme: "FaveKitPackageManager")
    # upload_to_testflight
    match(type: 'appstore', app_identifier: 'com.ios.FaveKitPackageManager')
    
    build_number = increment_build_number
    version_number = increment_version_number(bump_type: "patch")
    
    add_badge(shield: "#{version_number}-#{build_number}-red")

    gym

    pilot(username: "klearningapps@gmail.com")

  end
end